name: yy
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - pytorch
  - numba/label/dev
  - conda-forge
  - conda-forge/label/gcc7
  - conda-forge/label/broken
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - soumith
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - peterjc123
  - defaults
dependencies:
  - cudatoolkit
  - pytorch=1.3.0
  - torchvision
  - pydicom
  - tensorboard=1.14.0
  - tqdm
  - pandas
  - opencv
  - matplotlib
#  - python=3.5.5
#  - pytorch=0.4.1
  - scipy
  - pip:
    - dominate==2.3.1
    - git+https://github.com/pytorch/vision.git
    - Pillow==5.0.0
#    - numpy==1.14.1
    - visdom==0.1.7
